spring.application.name=baozi-store

spring.datasource.url=jdbc:mysql://localhost:3306/baozi_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mySql_vini@oP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true